import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// ✅ Se importan fuentes y estilos globales.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// 🔹 Configura una fuente sans-serif para todo el proyecto, usando variables CSS.

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// 🔹 Configura una fuente monoespaciada (tipo consola o código).

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 🔸 Metadata que aparecerá en el head del HTML.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 🔹 Este layout envuelve todas las páginas de la app.
  // Todo lo que pongas aquí (header, footer, etc.) se verá en todas las rutas.

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // antialiased → mejora la suavidad del texto (mejor renderizado de fuentes)
      >
        {children}
      </body>
    </html>
  );
}
